spring:
  datasource:
    url: jdbc:mysql://localhost:3306/remind-me
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080

web:
  url: http://localhost:3000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web: DEBUG
    com.coxautodev.graphql: DEBUG

facebook:
    client:
      clientId: 234613290655276
      clientSecret: f9fcbcbf70955aa457e6f1ee82e41728
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://graph.facebook.com/me

google:
    client:
      clientId: 831131574371-5sapum9ebgjo40vcdnjk4al1bg3g48mp.apps.googleusercontent.com
      clientSecret: ORFl9s6GgbhssiGYstjvgK1G
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile, email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false