# Enabling H2 Console:
spring:
  h2:
    console:
      enabled: true
  datasource:
     url: jdbc:h2:~/test
     driver-class-name: org.h2.Driver
     username: sa
     password:
server:
  port: 8011



logging:
  level:
    org.hibernate.SQL: DEBUG
